In [1]:
import numpy as np

### Creating numpy Arrays

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3], [1, 2, 3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
np.array([1, 2, 3], dtype="float64")

array([1., 2., 3.])

In [6]:
np.array((1, 2, 3))

array([1, 2, 3])

In [15]:
# use shape tuple
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# use shape tuple
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.random.randn(2)

array([0.19028273, 0.93243443])

In [20]:
# note: not shape tuple
np.random.randn(2, 3)

array([[ 0.07878894, -1.71980333,  1.27977103],
       [-0.09296889, -0.01863794, -0.19409763]])

In [22]:
np.random.randint(1, 6, 5)

array([3, 2, 1, 1, 4])

In [24]:
arr = np.random.randint(1, 6, (3, 5))

In [25]:
arr

array([[3, 1, 5, 2, 3],
       [1, 1, 4, 5, 4],
       [1, 3, 5, 2, 5]])

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr.ndim

2

In [28]:
arr.shape

(3, 5)

In [29]:
arr.reshape((15,))

array([3, 1, 5, 2, 3, 1, 1, 4, 5, 4, 1, 3, 5, 2, 5])

In [30]:
arr

array([[3, 1, 5, 2, 3],
       [1, 1, 4, 5, 4],
       [1, 3, 5, 2, 5]])

In [32]:
arr.shape = (15,)

In [33]:
arr

array([3, 1, 5, 2, 3, 1, 1, 4, 5, 4, 1, 3, 5, 2, 5])

In [34]:
arr + 5

array([ 8,  6, 10,  7,  8,  6,  6,  9, 10,  9,  6,  8, 10,  7, 10])

In [35]:
arr

array([3, 1, 5, 2, 3, 1, 1, 4, 5, 4, 1, 3, 5, 2, 5])

In [36]:
arr * 2

array([ 6,  2, 10,  4,  6,  2,  2,  8, 10,  8,  2,  6, 10,  4, 10])

In [37]:
arr + np.ones((15,))

array([4., 2., 6., 3., 4., 2., 2., 5., 6., 5., 2., 4., 6., 3., 6.])

In [38]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [39]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
a[1]

array([[5, 6],
       [7, 8]])

In [41]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [42]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
a[0] = [987, 987]

In [44]:
a

array([[[987, 987],
        [987, 987]],

       [[  5,   6],
        [  7,   8]]])

In [46]:
arr = np.arange(36).reshape(4, 3, 3)

In [47]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [48]:
arr[1:3, :2, 1:]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

In [49]:
arr = np.arange(9).reshape((3, 3))

In [50]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr[:2, :2]

array([[0, 1],
       [3, 4]])

In [52]:
arr[-1]

array([6, 7, 8])

In [53]:
arr[:, -1]

array([2, 5, 8])

In [54]:
a = np.arange(24).reshape((3, 4, 2))

In [55]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [56]:
a[[True, True, False]]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [57]:

a[:2]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [58]:
a[:2, [True, False, False, True]]

array([[[ 0,  1],
        [ 6,  7]],

       [[ 8,  9],
        [14, 15]]])

In [59]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a = np.arange(9).reshape((3,3))

In [63]:
a[[0, -1]]

array([[0, 1, 2],
       [6, 7, 8]])

In [64]:
a[[0, -1, -1]]

array([[0, 1, 2],
       [6, 7, 8],
       [6, 7, 8]])

In [65]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
a.mean()

4.0

In [68]:
a.mean(axis=0)

array([3., 4., 5.])

In [69]:
a = np.arange(18).reshape(2, 3, 3)

In [70]:
a.mean()

8.5

In [73]:
a.mean(axis=0)

array([[ 4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5],
       [10.5, 11.5, 12.5]])

In [72]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [74]:
a = np.arange(9)

In [75]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True])

In [76]:
a = np.arange(9).reshape((3, 3))

In [77]:
a > 3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [79]:
np.where(a > 5, 'big', 'smol')

array([['smol', 'smol', 'smol'],
       ['smol', 'smol', 'smol'],
       ['big', 'big', 'big']], dtype='<U4')